"""empty message

Revision ID: 0ac04a4aacb6
Revises: 8e36643494a7
Create Date: 2021-12-10 15:12:51.561035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ac04a4aacb6'
down_revision = '8e36643494a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('company_status', sa.Enum('Active', 'Inactive', name='status'), nullable=True))
    op.add_column('company_division', sa.Column('cmpy_divsionstatus', sa.Enum('Active', 'Inactive', name='status'), nullable=True))
    op.add_column('external_export_query_list', sa.Column('query_status', sa.Enum('Active', 'Inactive', name='status'), nullable=True))
    op.add_column('external_export_query_params', sa.Column('param_status', sa.Enum('Active', 'Inactive', name='status'), nullable=True))
    op.add_column('external_export_query_timer', sa.Column('timer_type', sa.Enum('Daily', 'Weekly', name='timer'), nullable=True))
    op.add_column('external_export_query_timer', sa.Column('timer_status', sa.Enum('Active', 'Inactive', name='status'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('external_export_query_timer', 'timer_status')
    op.drop_column('external_export_query_timer', 'timer_type')
    op.drop_column('external_export_query_params', 'param_status')
    op.drop_column('external_export_query_list', 'query_status')
    op.drop_column('company_division', 'cmpy_divsionstatus')
    op.drop_column('company', 'company_status')
    # ### end Alembic commands ###
