"""empty message

Revision ID: 8e36643494a7
Revises: 
Create Date: 2021-12-10 15:12:04.105437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e36643494a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('company_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.String(length=50), nullable=True),
    sa.Column('company_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('external_export_query_timer',
    sa.Column('query_timer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timer_company_id', sa.Integer(), nullable=False),
    sa.Column('timer_division_id', sa.Integer(), nullable=False),
    sa.Column('timer_company_url', sa.Text(), nullable=False),
    sa.Column('timer_time', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('query_timer_id')
    )
    op.create_table('company_division',
    sa.Column('cmpy_divsionid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cmpy_divsionname', sa.String(), nullable=True),
    sa.Column('cmpy_divisionemail', sa.String(), nullable=True),
    sa.Column('cmpy_companyid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cmpy_companyid'], ['company.company_id'], ),
    sa.PrimaryKeyConstraint('cmpy_divsionid')
    )
    op.create_table('external_export_query_list',
    sa.Column('query_list_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query_company_id', sa.Integer(), nullable=True),
    sa.Column('query_division_id', sa.Integer(), nullable=True),
    sa.Column('query_type', sa.String(), nullable=True),
    sa.Column('sp_name', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['query_division_id'], ['company_division.cmpy_divsionid'], ),
    sa.PrimaryKeyConstraint('query_list_id')
    )
    op.create_table('ftpserverdetails',
    sa.Column('sever_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('server_divisionid', sa.Integer(), nullable=True),
    sa.Column('server_host', sa.String(), nullable=False),
    sa.Column('server_name', sa.String(), nullable=False),
    sa.Column('server_password', sa.String(), nullable=False),
    sa.Column('server_folderpath', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['server_divisionid'], ['company_division.cmpy_divsionid'], ),
    sa.PrimaryKeyConstraint('sever_id')
    )
    op.create_table('sendingmail',
    sa.Column('send_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('send_cmpy_divid', sa.Integer(), nullable=True),
    sa.Column('send_email_tocc', sa.String(), nullable=False),
    sa.Column('send_emailid', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['send_cmpy_divid'], ['company_division.cmpy_divsionid'], ),
    sa.PrimaryKeyConstraint('send_id')
    )
    op.create_table('external_export_query_params',
    sa.Column('query_param_list_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query_list_id_fk', sa.Integer(), nullable=True),
    sa.Column('param_type', sa.String(), nullable=True),
    sa.Column('param_name', sa.String(), nullable=True),
    sa.Column('param_position', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['query_list_id_fk'], ['external_export_query_list.query_list_id'], ),
    sa.PrimaryKeyConstraint('query_param_list_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('external_export_query_params')
    op.drop_table('sendingmail')
    op.drop_table('ftpserverdetails')
    op.drop_table('external_export_query_list')
    op.drop_table('company_division')
    op.drop_table('external_export_query_timer')
    op.drop_table('company')
    # ### end Alembic commands ###
